mpi:
  - mpich
  - openmpi
  - nompi
c_stdlib:                      # [linux]
  - sysroot                    # [linux]
c_stdlib_version:              # [linux]
  - 2.17                       # [linux]
