{% set build = 4 %}
{% set name = "lammps" %}
{% set version = "patch_28Mar2023_update1" %}
{% set version_plugins = "patch_22Dec2022" %}
{% set sha256 = "dca4fb5747668c8c9a6d62d3f8c8637d06da9801f2b119a9a61e74eb7275ef2b" %}
{% set date = datetime.datetime.strptime(version.split('_')[1], "%d%b%Y") %}
{% set conda_version = "{:%Y.%m.%d}".format(date) %}

package:
  name: {{ name|lower }}
  version: {{ conda_version }}

source:
  - fn: {{ name }}-{{ conda_version }}.tar.gz
    url: https://github.com/lammps/lammps/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches: 
      - macos_install.patch
      - vcsgc_mtp_n2p2.patch
      - fix-cython.patch
  - fn: lammps-plugins.tar.gz
    url: https://github.com/lammps/lammps-plugins/archive/{{ version_plugins }}.tar.gz
    sha256: 455eae954314e8d51999be89ffdcc3f310cd3907810983dc998f7d1f8d73522e
    folder: lammps-plugins
  - fn: mlip.tar.gz
    url: https://gitlab.com/ashapeev/interface-lammps-mlip-2/-/archive/dd71d892c590fe79c9800946dc8984de91c05480/interface-lammps-mlip-2-master.tar.gz
    sha256: ee720576097469e2c66db75625362a5e649a64fff7bddc9d0e36959bce4d72ff
    folder: mlip
    patches:
      - mlip.patch
    
build:
  number: {{ build }}
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ mpi }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ mpi }}_{{ PKG_BUILDNUM }}                                                 # [cuda_compiler_version == "None"]
  skip: True  # [win]
  skip: True  # [cuda_compiler_version == "10.2"]
  track_features:
    - cudatoolkit               # [cuda_compiler_version != "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ compiler('cuda') }}    # [cuda_compiler_version != "None"]
    - sysroot_linux-64 2.17  # [linux]
    - cmake
    - make
    - pkg-config
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - cython
    - numpy
    - setuptools
    - pip
    - {{ mpi }}
    - zlib
    - fftw
    - hdf5
    - libpng
    - libjpeg-turbo
    - libcblas  # [linux]
    - libblas  # [linux]
    - liblapack  # [linux]
    - libnetcdf
    - kim-api
    - libcurl
    - mpi4py
    - mlip  # [linux]
    - n2p2 =2.2.0  # [linux]
    - quippy =0.9.12  # [linux]
    - voro
    - plumed

  run:
    - python
    - setuptools
    - {{ mpi }}
    - {{ pin_compatible("numpy") }}
    - kim-api
    - mlip  # [linux]
    - n2p2 =2.2.0  # [linux]
    - quippy =0.9.12  # [linux]
    - voro
    - plumed
    - __cuda  # [cuda_compiler_version != "None"]

test:
  imports:
    - lammps
  commands: 
    - lmp_serial -help > help_serial.txt  # [cuda_compiler_version == "None"]
    - mpiexec -n 1 lmp_mpi -help > help_mpi.txt  # [mpi == 'mpich' and cuda_compiler_version == "None"] 

about:
  home: http://lammps.sandia.gov
  license: GPL-2.0-only
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'LAMMPS stands for Large-scale Atomic/Molecular Massively Parallel Simulator.'

  description: |
    LAMMPS is a classical molecular dynamics simulation code designed to
    run efficiently on parallel computers.  It was developed at Sandia
    National Laboratories, a US Department of Energy facility, with
    funding from the DOE.  It is an open-source code, distributed freely
    under the terms of the GNU Public License (GPL).
  doc_url: http://lammps.sandia.gov/doc/Manual.html
  dev_url: https://github.com/lammps/lammps

extra:
  recipe-maintainers:
    - jan-janssen
    - ellio167
