travis:
  secure:
    BINSTAR_TOKEN: Ce78za8ivNHMenToXyHeSx2wfxvENTWne9VApYvg2wk2zeHxghZNOQIyWNJO3xz+hwvMh5bYeSMV6eR0ydex7pRY36PupwSSSvjGzcXrUBBLeTtQzlQd5ZcVddaBYdgOolpQHCBd5NOwHefeUu3LWmlStBT/siCc/fZTUZ9zSJtvqeQ9czYlI+CSKqfChxxfTFAUYKXh/pKATbZcMeIkNk79E3i8rDPviAEIYdieDCAx8fmib4NDiNpOQN3uq+EfMZYjuROGh36Nn0kcllIZWcqI1sjGJvl47o8opXr6lRcjJvtvdA2VnDzoXtregMfZZqvjFVRQuUeEBLEd8xJ8O2ZGh4/6ph6KsAJTcKzpyjy+sJfAedu6up+GgqwsMFS4nljukJR1PBsk5L7XQKUBoQYJk0+ev458264XYbmwjQU8+iBjt3LJQYqv7qg+pnrakOpyCZOqjcFTRsyH9WZ/HQFXnkT96E/U82L8JAZw6tk6PsAKS/t5Jq16qrcZMmF7dA2iW1AE773O0h8NopOg1y5b83EDL81k85U+Hpyrz9typdtUPKL2poYguxRzKodnDk8Rbp/mLpNUEZNgWlPcoicsVqd/FcWIsyzzbR3oLYS6A0Woi3oh4rNBJ0eNtdkiYOXc2eSUL/fi0qNZ+GazL/m5swWaHrZ7j3BH6ODx2m4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
